=== Luita7/Melola_LM-03-2023-24/ejercicios/factura/factura.dtd
<!ELEMENT factura (datos-emisor,datos-cliente,detalle-factura)>
<!ATTLIST factura numero NMTOKEN #REQUIRED>
<!ATTLIST factura fecha CDATA #REQUIRED>

<!ELEMENT datos-emisor (nombre,cif,telefono)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT cif (#PCDATA)>
<!ELEMENT telefono (#PCDATA)>

<!ELEMENT datos-cliente (nombre,cif,telefono)>

<!ELEMENT detalle-factura (articulo+)>
<!ATTLIST detalle-factura importe NMTOKEN #REQUIRED>
<!ATTLIST detalle-factura divisa NMTOKEN #REQUIRED>

<!ELEMENT articulo (descripcion,cantidad,oferta?,pvp)>
<!ATTLIST articulo codigo ID #REQUIRED>
<!ATTLIST articulo tipo (Libro|DVD|Varios) #IMPLIED>

<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT cantidad (#PCDATA)>
<!ELEMENT oferta EMPTY>
<!ELEMENT pvp (#PCDATA)>

=== Luita7/Melola_LM-03-2023-24/ejercicios/factura/factura.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE factura SYSTEM "factura.dtd">
<factura numero="27" fecha="18/12/2013">
    <!-- Hay que guardar los datos del emisor de la factura agrupados. A continuación, los datos del cliente, también agrupados. Y finalmente, los datos de detalle donde se escriben (en líneas) los datos de cada artículo, así como, el importe total. -->
    <datos-emisor>
        <nombre>Librería Pérez</nombre>
        <cif>4455566B</cif>
        <telefono>777777777</telefono>
    </datos-emisor>

    <datos-cliente>
        <nombre>Biblioteca Pérez</nombre>
        <cif>4455566A</cif>
        <telefono>777777777</telefono>
    </datos-cliente>

    <detalle-factura importe="85" divisa="euro">
        <articulo codigo="AW7" tipo="Libro">
            <descripcion>analítica Web</descripcion>
            <cantidad>1</cantidad>
            <oferta/>
            <pvp>25</pvp>
        </articulo>
        <articulo codigo="CP5" tipo="DVD">
            <descripcion>Curso de HTML</descripcion>
            <cantidad>2</cantidad>
            <pvp>30</pvp>
        </articulo>
    </detalle-factura>
</factura>
