=== Luita7/Melola_LM-03-2023-24/ejercicios/mensajes/mensajes2.dtd
<!ELEMENT mensajes (mensaje+)>
<!ELEMENT mensaje (telefonos,fechaEnvio,horaEnvio,texto+)>

<!-- O MÓVIL O FIJO -->
<!--<!ELEMENT telefonos (movil|fijo)> -->

<!-- Debe aparecer o móvil o fijo -->
<!-- Lo que genera VSC no permite alternativa. Es incorrecto -->
<!--<!ELEMENT telefonos (movil?,fijo?)>-->

<!-- DEBE TENER MÓVIL Y FIJO EN CUALQUIER ORDEN -->
<!ELEMENT telefonos (movil|fijo)*>

<!ELEMENT movil (#PCDATA)>
<!ELEMENT fechaEnvio (#PCDATA)>
<!ELEMENT horaEnvio (#PCDATA)>
<!ATTLIST horaEnvio franja CDATA #REQUIRED>
<!ELEMENT texto (#PCDATA)>
<!ELEMENT fijo (#PCDATA)>

=== Luita7/Melola_LM-03-2023-24/ejercicios/mensajes/mensajes.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mensajes SYSTEM "mensajes2.dtd">
<mensajes>
    <mensaje>
        <telefonos>
            <movil>666666666</movil>
            <fijo>918888888</fijo>
        </telefonos>
        <fechaEnvio>25/09/2023</fechaEnvio>
        <horaEnvio franja="GMT+1">12:45</horaEnvio>
        <texto>Mi primer mensaje 1</texto>
        <texto>Mi primer mensaje 2</texto>
        <texto>Mi primer mensaje 3</texto>
    </mensaje>
    <mensaje>
        <telefonos>
            <fijo>818888888</fijo>
            <movil>666666666</movil>
        </telefonos>
        <fechaEnvio>25/09/2023</fechaEnvio>
        <horaEnvio franja="GMT+1">12:45</horaEnvio>
        <texto>Mi segundo mensaje</texto>
    </mensaje>
</mensajes>
