=== Luita7/Melola_LM-03-2023-24/ejercicios/boletinNotas/boletin.dtd
<!-- Como mínimo debe ir un botelín -->
<!ELEMENT boletines (boletin)+>

<!ELEMENT boletin (datosAlumno,calificaciones)>

<!-- el orden del nombre, apellido y dirección del alumno no puede variar-->
<!ELEMENT datosAlumno (nombre,apellido,direccion?)>

<!-- el orden del nombre, apellido y dirección del alumno SI puede variar-->
<!--<!ELEMENT datosAlumno (nombre|apellido|direccion)+>-->

<!ELEMENT nombre (#PCDATA)>

<!ELEMENT apellido (#PCDATA)>
<!ELEMENT direccion (calle,ciudad,provincia)>
<!ATTLIST direccion CP NMTOKEN #REQUIRED>
<!ELEMENT calle (#PCDATA)>
<!ATTLIST calle numero NMTOKEN #REQUIRED>
<!ATTLIST calle piso NMTOKEN #REQUIRED>
<!ATTLIST calle letra NMTOKEN #REQUIRED>
<!ELEMENT ciudad (#PCDATA)>
<!ELEMENT provincia (#PCDATA)>
<!ELEMENT calificaciones (modulos)>
<!ELEMENT modulos (modulo+)>
<!ELEMENT modulo (calificacion+)>
<!ATTLIST modulo id ID #REQUIRED>
<!ATTLIST modulo nombre CDATA #REQUIRED>
<!ELEMENT calificacion (#PCDATA)>
<!ATTLIST calificacion tipo NMTOKEN #REQUIRED>

=== Luita7/Melola_LM-03-2023-24/ejercicios/boletinNotas/boletin.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE boletines SYSTEM "boletin.dtd">
<boletines>
    <boletin>
        <datosAlumno>
            <nombre>Isaac</nombre>
            <apellido>Pérez</apellido>
            <direccion CP="28805">
                <calle numero="6" piso="3" letra="C">Del Pez</calle>
                <ciudad>Alcalá de Henares</ciudad>
                <provincia>Madrid</provincia>
            </direccion>
        </datosAlumno>
        <calificaciones>
            <modulos>
                <modulo id="LM" nombre="Lenguajes de marcas">
                    <!--<nombre>Lenguajes de marcas</nombre>-->
                    <calificacion tipo="1ev">5</calificacion>
                    <calificacion tipo="2ev">7</calificacion>
                    <calificacion tipo="3ev">8</calificacion>
                    <calificacion tipo="ordinaria">7</calificacion>
                </modulo>
                <modulo id="PROG" nombre="Programacion">
                    <!--<nombre>Lenguajes de marcas</nombre>-->
                    <calificacion tipo="1ev">5</calificacion>
                    <calificacion tipo="2ev">7</calificacion>
                    <calificacion tipo="3ev">8</calificacion>
                    <calificacion tipo="ordinaria">7</calificacion>
                </modulo>
            </modulos>
        </calificaciones>
    </boletin>

    <boletin>
        <datosAlumno>
            <nombre>Isaac</nombre>
            <apellido>Pérez</apellido>
            <direccion CP="28805">
                <calle numero="6" piso="3" letra="C">Del Pez</calle>
                <ciudad>Alcalá de Henares</ciudad>
                <provincia>Madrid</provincia>
            </direccion>
        </datosAlumno>
        <calificaciones>
            <modulos>
                <modulo id="LM" nombre="Lenguajes de marcas">
                    <!--<nombre>Lenguajes de marcas</nombre>-->
                    <calificacion tipo="1ev">5</calificacion>
                    <calificacion tipo="2ev">7</calificacion>
                    <calificacion tipo="3ev">8</calificacion>
                    <calificacion tipo="ordinaria">7</calificacion>
                </modulo>
                <modulo id="PROG" nombre="Programacion">
                    <!--<nombre>Lenguajes de marcas</nombre>-->
                    <calificacion tipo="1ev">5</calificacion>
                    <calificacion tipo="2ev">7</calificacion>
                    <calificacion tipo="3ev">8</calificacion>
                    <calificacion tipo="ordinaria">7</calificacion>
                </modulo>
            </modulos>
        </calificaciones>
    </boletin>
    
</boletines>
