=== Luita7/Melola_LM-03-2023-24/ejercicios/biblioteca/biblioteca.dtd
<!ELEMENT biblioteca (libro+)>
<!ELEMENT libro (titulo,edicion,editorial,ISBN,numPags,autores)>
<!ATTLIST libro codigo NMTOKEN #REQUIRED>
<!ATTLIST libro tipo NMTOKEN #IMPLIED>
<!ATTLIST libro otro CDATA #IMPLIED>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT edicion (#PCDATA)>
<!ELEMENT editorial (#PCDATA)>
<!ELEMENT ISBN (#PCDATA)>
<!ELEMENT numPags (#PCDATA)>
<!--<!ELEMENT autores (autor|autora)*>-->
<!ELEMENT autores (autor|autora)+>
<!ELEMENT autor (#PCDATA)>
<!ELEMENT autora (#PCDATA)>

=== Luita7/Melola_LM-03-2023-24/ejercicios/biblioteca/biblioteca.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE biblioteca SYSTEM "biblioteca.dtd">
<biblioteca>
    <libro codigo="L1" tipo="tapaDura" otro="cualquier cosa!">
        <titulo>lakjsdfasdf</titulo>
        <edicion>primera</edicion>
        <editorial>asdf</editorial>
        <ISBN>asdfasdfasdf</ISBN>
        <numPags>225</numPags>
        <autores>
            <autor id="a1">Pepito</autor>
            <autor id="a2">Pepito2</autor>
            <autora>Mari</autora>
            <autor>Menganito</autor>
        </autores>
    </libro>
    <libro codigo="L2" tipo="tapaBlanda">
        <titulo>lakjsdfasdf</titulo>
        <edicion>primera</edicion>
        <editorial>asdf</editorial>
        <ISBN>asdfasdfasdf</ISBN>
        <numPags>225</numPags>
        <autores>
            <autora>Pepita</autora>
            <autora>Mari</autora>
            <autor>Menganito</autor>
        </autores>
    </libro>
    <libro codigo="L3">
        <titulo>lakjsdfasdf</titulo>
        <edicion>primera</edicion>
        <editorial>asdf</editorial>
        <ISBN>asdfasdfasdf</ISBN>
        <numPags>225</numPags>
        <autores>
            <autor>Pepito</autor>
            <autor>Pepito2</autor>
            <autora>Mari</autora>
            <autor>Menganito</autor>
        </autores>
    </libro>

</biblioteca>
