=== Luita7/Melola_LM-03-2023-24/ejemplosDeClase/empleados/empleados1.dtd
<!ELEMENT empleados (empleado*)>
<!ELEMENT empleado (nombre,apellidos,(movil|fijo),direciones?)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT movil (#PCDATA)>
<!ELEMENT direciones (direccion+)>
<!ELEMENT direccion (#PCDATA)>
<!ELEMENT fijo (#PCDATA)>

=== Luita7/Melola_LM-03-2023-24/ejemplosDeClase/empleados/empleados.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE empleados SYSTEM "empleados1.dtd">
<empleados>
    <empleado>
        <nombre>kk</nombre>
        <apellidos>klkjlk</apellidos>
        <movil>66666666</movil>
        <direciones>
            <direccion>dir1</direccion>
            <direccion>dir2</direccion>
        </direciones>
    </empleado>
    <empleado>
        <nombre>kk</nombre>
        <apellidos>klkjlk</apellidos>
        <fijo>66666666</fijo>
    </empleado>
</empleados>
